name: 'Hatch'
description: 'Generate and publish a TypeScript-axios API client based on your OpenAPI spec'
inputs: 
  path-to-json:
    description: 'Path to JSON-formatted OpenAPI spec'
    required: true
  service-name:
    description: 'Your service name (client will be published as your-service-name-client)'
    required: true
  github-registry-token:
    description: 'Your GitHub Registry token'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path-to-json }}
    - ${{ inputs.service-name }}
    - ${{ inputs.github-registry-token }}
