name: 'Hatch'
description: 'Generate and publish a TypeScript-axios API client based on your OpenAPI spec'
inputs: 
  path:
    description: 'Path to JSON-formatted OpenAPI spec'
    required: true
  name:
    description: 'Your service name (client will be published as your-service-name-client)'
    required: true
  token:
    description: 'Your GitHub Registry token'
    required: true
  registry_namespace:
    description: 'Name of your GitHub NPM registry namespace (without the "@" where applicable)'
    required: true
  repo_url:
    description: 'Your GitHub repository clone url'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - INPUT_PATH
    - INPUT_NAME
    - INPUT_TOKEN
    - INPUT_REGISTRY_NAMESPACE
    - INPUT_REPO_URL
