name: 'Hatch'
description: 'Generate and publish a TypeScript-axios API client based on your OpenAPI spec'
inputs: 
  path:
    description: 'Path to JSON-formatted OpenAPI spec'
    required: true
  name:
    description: 'Your service name (client will be published as your-service-name-client)'
    required: true
  token:
    description: 'Your GitHub Registry token'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
    - ${{ inputs.name }}
    - ${{ inputs.token }}
