#!/usr/bin/env sh

# pull in jq (for json string building)
apt-get update
apt-get -y install jq

# pull openapi-generator binary
wget --quiet https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/4.2.3/openapi-generator-cli-4.2.3.jar -O openapi-generator-cli.jar

if [ $? -ne 0 ]
then
  echo "Error downloading openapi generator binary; aborting."
  exit 1
fi

# run generator
java -jar openapi-generator-cli.jar generate \
    --input-spec $INPUT_PATH \
    --generator-name typescript-axios \
    --additional-properties=supportsES6=true,modelPropertyNaming=original,withInterfaces=true \
    --output /client

if [ $? -ne 0 ]
then
  echo "Something went wrong running the openapi generator; aborting."
  exit 1
fi

cd /client

# write package.json with package name, description, version, and github repo
DATE=$(date -u +"%Y%m%d%H%M%S")
cat package.json.template | jq --arg pn "$INPUT_NAME" '.name="@birdiecare/\($pn)-client"' | jq --arg pn "$INPUT_NAME" '.description="Autogenerated API client for \($pn) service."' | jq --arg pn "$INPUT_NAME" '.repository.url="ssh://git@github.com/birdiecare/\($pn).git"' | jq --arg date "$DATE" '.version="0.0.\($date)"' > package.json

if [ $? -ne 0 ]
then
  echo "Something went wrong writing package.json; aborting."
  exit 1
fi

# install dependencies and build
npm i
npm run build

if [ $? -ne 0 ]
then
  echo "Failed to build package; aborting"
  exit 1
fi

# copy package.json to dist folder and publish to GitHub package registry
cp package.json dist/
cd dist
echo "@birdiecare:registry=https://npm.pkg.github.com/" >> .npmrc
echo "//npm.pkg.github.com/:_authToken=$INPUT_TOKEN" >> .npmrc
npm publish

if [ $? -ne 0 ]
then
  echo "Something went wrong publishing the NPM package."
  exit 1
else
  echo "Hatch action completed successfully."
  exit 0
fi
